### PR TITLE
Orient belt helper for printing.

### PR DESCRIPTION
**Pull request by viesturz**
Just placing them at the correct orientation.

### CODE REVIEW

**Comment by Hellsparks** [comment]
thank you!

did they prove useful?

**Comment by viesturz** [comment]
Still printing, will know is an hour.

**Comment by viesturz** [comment]
Mostly worked. The size is too small for tapchanger shuttle however.
PXL_20240517_164807381 MP

**Comment by Hellsparks** [comment]
not the intended usecase but it works kinda😅, you should push the 6mm belts towards eachother by the cilps though.

**Comment by viesturz** [comment]
I added the extra long screws to give the belt enough slack to make it work
:P

**Pull request merged**
